# A debugging utility for testing Minio from within k8s.
apiVersion: v1
kind: Pod
metadata:
  name: deis-slugbuilder
  labels:
    heritage: deis
    version: 2015-sept
spec:
  restartPolicy: Never
  containers:
    - name: deis-slugbuilder
      imagePullPolicy: Always
      image: quay.io/deisci/slugbuilder:v2-alpha
      env:
        - name: DEBUG
          value: "1"
        - name: TAR_URL
          value: "https://s3.amazonaws.com/mydaffa/mytar.tgz"
        - name : put_url
          value: "https://s3-us-west-1.amazonaws.com/myjaffa"
      volumeMounts:
        - name: object-store
          mountPath: /var/run/secrets/object/store
          readOnly: true
  volumes:
    - name: object-store
      secret:
        secretName: object-store
